### PR TITLE
Removed GI from join table. Added error handling.

### PR DESCRIPTION
**Pull request by JacobPorter**

### CODE REVIEW

**Comment by nconrad** [comment]
@JacobPorter On comments: unless there is some sort of value, or the piece of code may be re-add be in the short term, could you remove any commented code and console logs?  If it actually something of value, it'd help to put a comment about why the piece is commented out.  Sound reasonable?  

https://github.com/PATRIC3/p3_web/pull/1003/commits/3be6030e81a6ae39bcf6f589807f5eff3bc5c3f8#diff-cbf8544ed1f6a8e3d66871a7af3f4ee1R513-R533. I understand sometimes the comments come from other, existing piece of code, just don't want to introduce more.

**Review by nconrad — CHANGES_REQUESTED** [review]
@JacobPorter On comments: unless there is some sort of value, or the piece of code may be re-add in the short term, could you remove any commented code and console logs? If it is actually something of value, it'd help to put a comment about why the piece is commented out. Sound reasonable?

https://github.com/PATRIC3/p3_web/commit/3be6030e81a6ae39bcf6f589807f5eff3bc5c3f8#diff-cbf8544ed1f6a8e3d66871a7af3f4ee1R513-R524. I understand sometimes the comments come from other, existing piece of code; I just don't want to introduce more.

**Comment by JacobPorter** [comment]
@nconrad Commented code and unnecessary console logs were removed.  Console logs for error handlers were left in.  This is consistent with existing behavior.

**Comment by nconrad** [comment]
@JacobPorter Great, thanks.

**Comment by nconrad** [comment]
https://github.com/PATRIC3/patric3_website/issues/2370

**Pull request merged**
