### PR TITLE
updated metagenomic read mapping UI

### PR DESCRIPTION
**Pull request by dawenx**
and
added service entry for metagenomic read mapping
moved SRR validation text for comprehensive genome analysis service

### CODE REVIEW

**Comment by chris-c-thomas** [comment]
Is this what still has the small UI padding bug with the input @dawenx  ?

**Comment by dawenx** [comment]
@chris-c-thomas i will open a ticket for the UI padding bug in tree service, but this is not about that.

**Comment by chris-c-thomas** [comment]
@dawenx okay, I confused myself lol. Thanks.

**Comment by dawenx** [comment]
Since Codon tree method is supported in Phylogenetic Tree service UI now, I'm removing this standalone UI in checkin c4ce1d0

**Pull request merged**
