### PR TITLE
fixed issue #1452 and #1496

### PR DESCRIPTION
**Pull request by dawenx**
added fasta options in speciality genes download.

### CODE REVIEW

**Comment by hyoo** [comment]
No, this is not a right approach. sp_gene contains unique attributes that needs to be downloaded, which is a priority.

**Comment by dmachi** [comment]
I’m not sure what you mean.  This is when you select a number of specialty genes and want to be able to download that fasta associated with them.

**Comment by hyoo** [comment]
I might be wrong, I didn't tried but I guess the dataType (changed from sp_gene to genome_feature) will be used to select core. If so, you will ended up getting genome features while user expect to download specialty gene properties such as property, source, pmid, identity etc.

**Comment by dmachi** [comment]
I hadn't actually looked at the patch.  It does need additional work.  The way this was done it changed the 'table' downloads to also use genome_feature, when it needs to be done so that it normally uses the sp_gene core, but when downloading the other things then it uses the genome_feature core.

**Comment by dawenx** [comment]
My understanding was the content in the grids can be downloaded in csv/text format, when requesting download for DNA/Protein FASTA, we have to retrieve it from genome_feature table as there's such data in sp_gene. Can you try different download options there and let me know if that's not what we wanted?

**Comment by dmachi** [comment]
That is correct understanding, but I can look at this patch and see that when you do the table download (text/csv) it is going to download that from genome_feature instead of sp_gene.

**Comment by dawenx** [comment]
@dmachi table download (text/csv) issue in previous patch has been fixed. I also fixed issue 1496 and removed conf.field related logic.

**Comment by dawenx** [comment]
@hyoo @dmachi Just wondered whether one of you have time review this pull request, thanks.

**Pull request merged**
