### PR TITLE
Fixes assembly viewer not displaying for SARS2 analysis.

### PR DESCRIPTION
**Pull request by JacobPorter**
Example:
/workspace/anwarren@patricbrc.org/AndrewWarrenPublic/cov2/Severe acute respiratory syndrome coronavirus 2 cdc_snp_SRR11621984

### CODE REVIEW

**Comment by nconrad** [comment]
@JacobPorter This handles the assembly case, but we were wondering if this could be made generic in the sense that the navigation works for any `job_result` object that doesn't have a special viewer.  I.e., could there be a generic version of this https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/viewer/GenomeAssembly.js so that we don't need to create a stub for every new job_result type?  

The issue came up recently because now we have two code bases, where test.bv-brc.org has a "stub", but patricbrc.org does not, and so the navigation breaks.   Of course, if you can figure out the navigation issue, that's even better.

**Comment by nconrad** [comment]
I should have said, it may be that the logic should go in the base class.  https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/viewer/JobResult.js  I'll leave that to you to decide.... nobody has really worked on or 'owned' that code since it was created.

**Comment by JacobPorter** [comment]
Yeah, I am still looking at that.  I think that there is an issue with reusing the default JobResult viewer.  The viewer is used initially just fine, but using it again in the assembly object creates problems.

**Comment by JacobPorter** [comment]
I changed some logic to handle nested JobResult viewers.

**Pull request closed without merging**
