### PR TITLE
Cumulative Fixes

### PR DESCRIPTION
**Pull request by chris-c-thomas**
- Check for unique EC Numbers and display results: [#2318](https://github.com/PATRIC3/patric3_website/issues/2318)
- Check for unique Pathways and display results: [#2318](https://github.com/PATRIC3/patric3_website/issues/2318)
- Check for unique Subsystems and display subsystem_names + role_names: [#2318](https://github.com/PATRIC3/patric3_website/issues/2318)
- Update CGA Tutorial Link to revised edition

### CODE REVIEW

**Comment by nconrad** [comment]
1) @chris-c-thomas The lines like this one create arrays of size data.length with empty values between the unique values, right? https://github.com/PATRIC3/p3_web/pull/942/commits/fb08d7f9f385137147e38740dcdbd9e574861735#diff-a87e3dd9e029edf99137d562684a17ecR337
I'd consider that a bad practice.  You should use `array.push` instead.

2) although it works, `foo = foo += 'bar'`  should be `foo += 'bar'`  :)

There's a few other things I may suggest, but go ahead and fix that and we could pair program when I'm back.  I'll deploy when I'm back.  This is better overall.

**Comment by chris-c-thomas** [comment]
@nconrad 

1. I don't believe so. The array is used just a temp to check if the value is unique or not. The value is assigned if it isn't already in it so there shouldn't be any empty values.

2. Ahh same thinng but yeah I'll condense and update. 

Sounds good, would love to discuss and go over options when you get back.

**Comment by nconrad** [comment]
Here's an example:
```
> var foo = []
undefined
> foo[3] = 'bar'
'bar'
> foo[7] = 'bar2'
'bar2'
> foo
[ <3 empty items>, 'bar', <3 empty items>, 'bar2' ]
> foo.length
8
```

**Comment by chris-c-thomas** [comment]
It just clicked :)

**Pull request merged**
