### PR TITLE
Fixed genome search query issue with spaces

### PR DESCRIPTION
**Pull request by zreyn**
This is a quick fix, very specific to the genome name search.   It looked like farther upstream was dojo, so I didn't want to make a change there.  All this JS is loosely coupled, so let me know if I missed a link in the chain.

### CODE REVIEW

**Comment by zreyn** [comment]
Added additional filtering options (Representative and Reference) for the genome name search on the RNA Sequencing page.

**Comment by hyoo** [comment]
This looks okay, but I am not familiar with the problem this PR is purposed for. @aswarren or @dmachi , would you review and merge this?

**Comment by aswarren** [comment]
@zreyn There is a small issue here. The widget needs to search genome IDs which have a '.' in them. So stripping all special characters is a little over kill since it breaks searching for 83332.12
If we can get that working I'm fine with something like "MAP/TANUVAS/TN/India/2008" not working (though that is attached to a name of a genome). Let me know if you want to fix. If you make another pull request it will usurp this one right?

**Comment by zreyn** [comment]
Ahh, that makes sense.  I'll make the fix and submit another pull request.
It should bundle the changes.

Thanks!
-Zane

**Comment by zreyn** [comment]
I verified that searching for "83332.12" works as expected, as well as "brucella abortus rb51". 

There's some side effects of this.  In searching for "subsp. pneumophila" vs "subsp pneumophila", the first case yeilds the query "subsp.pneumophila" (which fails) and the second yeilds "subsppneumophila" (which works). I could try to make it so that periods between numbers do one thing vs periods among letters, but that might be a bit gnarly-looking.  

Let me know.

**Pull request merged**
