### PR TITLE
Bug fix: Numbers not appear on outside of circular viewer for private genomes #2355

### PR DESCRIPTION
**Pull request by chmao1**

### CODE REVIEW

**Comment by nconrad** [comment]
@chmao1 While you are fixing this...

There's a bigger issue where the circular viewer tab doesn't load at all.  I tracked down that it's due to 4 id attributes in https://github.com/PATRIC3/p3_web/blob/master/public/js/p3/widget/templates/TrackController.html

When you leave and go back to the tab, you'll see the dojo registry error locally:

image

I think it's safe to remove the 4 ids from the template, but could you check?

**Comment by dmachi** [comment]
@nconrad this is correct.  There should almost never be id's used in any templates.  Chunhong's commit otherwise looks fine.

**Comment by nconrad** [comment]
@dmachi ok, thanks. I'll make another PR for that.

**Comment by nconrad** [comment]
@dmachi @chmao1 It looks like the submodule commit isn't actually pushed to https://github.com/dmachi/circulus.git

```
fatal: reference is not a tree: 8b6dfaf0d15674d8becd1141d7326810eae69815
```

**Comment by chmao1** [comment]
@nconrad @dmachi I made a pull request at 
https://github.com/dmachi/circulus/pull/3

**Comment by dmachi** [comment]
I’ve merged this circulus pull.

**Pull request merged**
