### PR TITLE
icon for sorting

### PR DESCRIPTION
**Pull request by JoshuaVSherman**
https://github.com/PATRIC3/patric3_website/issues/1175

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
@nconrad @hyoo maybe your version is not new enough to use the one I was trying or maybe I can just remove it from the /p3 folder, let me try ones more

**Comment by nconrad** [comment]
@JoshuaVSherman yeah, I documented it.  It's a fairly complex process unfortunately. 

https://github.com/PATRIC3/p3_web/blob/master/docs/adding-icons.md

**Comment by dmachi** [comment]
I don’t know what the exact latest pattern for updating icons is, but we have been using icomoon.io to build our icon font for all or nearly all of our icons.  Font-Awesome was integrated through that I believe.

**Comment by JoshuaVSherman** [comment]
@hyoo @nconrad won't work unless I import to the css file

**Comment by JoshuaVSherman** [comment]
@hyoo all fixed now

**Comment by hyoo** [comment]
can someone in BI help Josh to resolve the submodule issue?

**Pull request merged**
