### PR TITLE
CSV/TSV Viewer; shortcut links on feature view

### PR DESCRIPTION
**Pull request by DinaBai**
Requesting alpha testing of tsv/csv table viewer.

### CODE REVIEW

**Comment by nconrad** [comment]
Hi @DinaBai and @aswarren, I changed the base branch to `feature/csv-viewer` to keep the development separate from releases.   There's a lot of changes, and so I'd like to look over some of them.  The linter check may have failed?  I'll take a look tomorrow.  thanks!

**Comment by aswarren** [comment]
@nconrad it probably appears to be more changes because the preview branch hasn't been updated in quite some time.

**Comment by nconrad** [comment]
@DinaBai @aswarren This is on alpha now.  Looks useful.  I didn't merge because of commit #fe383d2 (to be safe).  It may be good to have some public workspace CSV examples to share with the team?

**Comment by DinaBai** [comment]
@nconrad @aswarren Thanks for putting this on alpha.  Can I create a directory in the public workspace or does this require some permission I do not yet have?  I have not tried, but I will.  I will create a TSV/CSV Viewer Test folder and I can add the files I used for testing.  I can also add a readme.txt.  It would be good if testers also tried their own files though because perhaps other files will contain info I did not anticipate.

**Comment by DinaBai** [comment]
@nconrad @aswarren New folder in the public workspace called Test_CSV_TSV_Viewer contains three test files and a short readme file.  If you want me to add or change anything, let me know.  Thanks for your help.

**Comment by nconrad** [comment]
@DinaBai This is pretty cool.  This and the readme.txt helps a lot a summary.  Although I know ya'll had your discussions about why this is useful, if you are willing, this is probably one of those things that would make sense to present to the entire group on Tuesday.

I promise to stop commenting on PRs this late in evening.

**Comment by DinaBai** [comment]
@nconrad Thank you!  I can present it on Tuesday if Ron agrees there is time on the agenda.  

I promise to stop reading comments on this PR late in the evening, starting now...

**Pull request merged**
