### PR TITLE
fixes for multiple issues

### PR DESCRIPTION
**Pull request by JoshuaVSherman**

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/patric3_website/issues/1171

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/patric3_website/issues/1886

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/patric3_website/issues/1175

**Comment by JoshuaVSherman** [comment]
https://github.com/PATRIC3/patric3_website/issues/1902

**Comment by hyoo** [comment]
@JoshuaVSherman please separate bug fixes into multiple feature branches. Some of those fixes are controversial and cannot merge right now. for example, alphabetizing dropdown order is conflicting with some other request that people want to see recent group/folder show at the top, so that they can find it easily. So, we better to have provide both ways in stead of just replacing sorting condition.

**Comment by hyoo** [comment]
@JoshuaVSherman and please make two separate commits when you change something and reformatting. otherwise, it is *very* difficult to trace changes.

**Comment by JoshuaVSherman** [comment]
@hyoo I removed the changes to workspace object selector, i'll submit that in a different pull request

**Pull request merged**
